apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-didactic-unit
  namespace: cetpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-didactic-unit
  template:
    metadata:
      labels:
        app: ms-didactic-unit
    spec:
      containers:
        - name: ms-didactic-unit
          image: gabrielgutierrezquispe/vg-ms-didacticunit:1.0.0
          ports:
            - containerPort: 8087
          resources:
            requests:
              cpu: "0.25"  
              memory: "512Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"