apiVersion: v1
kind: Service
metadata:
  name: ms-didactic-unit
  namespace: cetpro
spec:
  selector:
    app: ms-didactic-unit
  ports:
    - name: http
      protocol: "TCP"
      port: 8087
      targetPort: 8087
  type: ClusterIP